### PR TITLE
1.13.1 Update

### PR DESCRIPTION
**Pull request by DrkMatr1984**
1.13.1 Update, no additional changes
[:package:  1.13.1](https://github.com/MinevoltRPG/BetterBlockBreaking/releases/tag/6.6.0-1.13.1)

### CODE REVIEW

**Comment by DrkMatr1984** [comment]
Updated to 1.14.4, Added official Towny Support for preventing animation
[:package:  1.14.4](https://github.com/MinevoltRPG/BetterBlockBreaking/releases/tag/6.6.0-1.14.4)

**Comment by DrkMatr1984** [comment]
Annnnnd 1.15 and 1.15.1 now also :P
[ :package: 1.15](https://github.com/MinevoltRPG/BetterBlockBreaking/releases/tag/6.6.0-1.15)

**Comment by SavageTheUnicorn** [comment]
Any plans for major versions, like 1.16.5 or 1.19.4 or 1.20.1 for example? I love this mod and I use it ACTIVELY. If I had any coding knowledge I'd definitely update it myself haha.

**Comment by DrkMatr1984** [comment]
It's been a while since I worked on this but was recently thinking about how great this plugin is. I don't know if Gustav has it in the works or not but maybe after working on another project I can give it some love.

**Comment by SavageTheUnicorn** [comment]
> It's been a while since I worked on this but was recently thinking about how great this plugin is. I don't know if Gustav has it in the works or not but maybe after working on another project I can give it some love.
> 

I'd be ecstatic if you did haha. I'd even be willing to put up like $15-25 for a bounty to get it for 1.16.5, 1.19.4, 1.20.1, and 1.21 when it's ready. That's asking quite alot for very little I know, but I have a family of 5 including myself 😅 maybe Gustav is, we'll have to get an answer instead of a commit merge to know for sure haha

**Comment by DrkMatr1984** [comment]
If I remember correctly it wasn't much work to update it. The trouble was that it uses NMS code and needs updated every update. Each version of the plugin only works for one version at a time. Mostly just requires decompiling the mc server source code and then trying to figure out what they renamed the methods to in the new version. 
Unfortunately if the methods have been changed too much the plugin may not function anymore, and while I have the code knowledge to update it, I don't really know enough about MC internal code to build it again from scratch. Let's keep our fingers crossed! 
No need for money or donation this time. Maybe if it becomes a regular thing I'll take a couple of coffees in exchange for bumping it to the newest server versions in the future.

**Comment by SavageTheUnicorn** [comment]
You're awesome haha. I appreciate the effort for sure 😊 it's definitely possible in 1.19+ as another plugin does the same thing already(with smoother animation ngl) but its heavily rpg centered with no way to disable most features. The 1.19 version is also crosscompatible with 1.20 using the same file so I'm unsure if they're using the same methods/nms for their work.
Either way, thank you for taking your time. As of right now I just want to get the 4 versions I've stated and possibly a 5th once 1.21 has a stable release for paper, but for sure I'm willing to support the efforts :)

**Comment by DrkMatr1984** [comment]
Yeah they use like a reflection method to get the different versions and then use the different version files for whichever. I'm too lazy for all that :P Maybe in the future I could do that since technically each version will already have the necesary code, so it would just be a matter of reassembling the project differently and learning how to make maven behave with the different versions, as well as my IDE :/

**Comment by SavageTheUnicorn** [comment]
It would be a learning experience at the very least lol

**Pull request merged**
